server.port: 8111

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

data.dir: C:\Users\User\projects\examples\upload-and-retrieve-images-sse